#------九龙峪管理站生产环境配置-----
ruoyi:
  profile: /project/tunnel/uploadPath
spring:
  # 数据源配置
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://10.7.187.35:3306/tunnel-jq?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: jq_user
        password: Platform123!@#
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: Redis123!@#
  kafka:
    wulian:
      #正式环境部署地址
      bootstrap-servers: 10.166.139.204:9092,10.166.139.205:9092,10.166.139.206:9092
    huawei:
      bootstrap-servers: 10.7.187.29:9092
      # 消费者
      consumer:
        # 消费者组
        group-id: HuaWeiGroup_Formal
        # 小车前端显示消费者组
        group-id-Two: HuaWeiGroup_Formal_Cat
    wanji:
      #非正式环境使用地址，避免接收推送数据
      bootstrap-servers: 10.7.187.35:9092
      # 生产者
      producer:
        # 重试次数，设置大于0的值，则客户端会将发送失败的记录重新发送
        retries: 3
        batch-size: 16384 #批量处理大小，16K
        buffer-memory: 33554432 #缓冲存储大，32M
        acks: 1
        # 指定消息key和消息体的编解码方式
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer

      # 消费者
      consumer:
        # 消费者组
        group-id: jlyGroup_Formal
        # 小车前端显示消费者组
        group-id-Two: jlyGroup_Formal_Cat
        # 是否自动提交
        enable-auto-commit: false
        # 消费偏移配置
        # none：如果没有为消费者找到先前的offset的值,即没有自动维护偏移量,也没有手动维护偏移量,则抛出异常
        # earliest：在各分区下有提交的offset时：从offset处开始消费；在各分区下无提交的offset时：从头开始消费
        # latest：在各分区下有提交的offset时：从offset处开始消费；在各分区下无提交的offset时：从最新的数据开始消费
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        max-poll-records: 500
      properties:
        max.poll.interval.ms: 1000000

#集团智慧大脑单点登录
sso:
  url: http://10.166.154.106:32725
  #智慧大脑单点登录跳转高速云级平台时，如果没有对应的用户，仍然可以进入隧道平台，使用此默认账号登录隧道平台
  defaultUser: admin_sso

device:
  hongmeng:
    #正式环境部署地址
    url: http://10.7.187.28:60400/qxsd-iot


#欧姆龙PLC通信的服务IP
plc:
  server: 10.7.187.35

#万集车流量
wj_carVolume: jly

tunnel_dept_id: 555503