#------九龙峪管理站生产环境配置-----
ruoyi:
  profile: /project/tunnel/uploadPath
spring:
  # 数据源配置
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://10.7.187.35:3306/tunnel-jq?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: jq_user
        password: Platform123!@#
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: Redis123!@#
  kafka:
    wulian:
      #正式环境部署地址
      bootstrap-servers: 10.166.139.204:9092,10.166.139.205:9092,10.166.139.206:9092
    huawei:
      bootstrap-servers: 10.7.187.29:9092
      # 消费者
      consumer:
        # 消费者组
        group-id: HuaWeiGroup_Formal
        # 小车前端显示消费者组
        group-id-Two: HuaWeiGroup_Formal_Cat

#集团智慧大脑单点登录
sso:
  url: http://10.166.154.106:32725
  #智慧大脑单点登录跳转高速云级平台时，如果没有对应的用户，仍然可以进入隧道平台，使用此默认账号登录隧道平台
  defaultUser: jlyadmin

device:
  hongmeng:
    #正式环境部署地址
    url: http://10.7.187.28:60400/qxsd-iot


#欧姆龙PLC通信的服务IP
plc:
  server: 10.7.187.35
