#------九龙峪管理站生产环境配置-----
ruoyi:
  profile: /project/tunnel/uploadPath
spring:
  # 数据源配置
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://10.7.179.15:3306/tunnel_hs?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: root
        password: zc123456
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
  kafka:
    wulian:
      #正式环境部署地址
      bootstrap-servers: 10.166.139.204:9092,10.166.139.205:9092,10.166.139.206:9092
    huawei:
      bootstrap-servers: 10.7.187.29:9092
      # 消费者
      consumer:
        # 消费者组
        group-id: HuaWeiGroup_Formal
        # 小车前端显示消费者组
        group-id-Two: HuaWeiGroup_Formal_Cat
device:
  hongmeng:
    #正式环境部署地址
    url: http://100.7.187.28:60400/qxsd-iot
