# 项目相关配置
ruoyi:
  # 名称
  name: Athena
  # 版本
  version: 1.3.7.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
#  profile: /Users/yqc/OpenSources/ruoyi
  profile: D:/project/tunnel/uploadPath
#  profile: E:/
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

  # 文件上传 本地: local  阿里云： alioss
  uploadType: local
  # 阿里云oss存储配置
  oss:
    bucketName: bucket-wisdom-oss
    # 这个需要在高速云网络环境下才可以访问，如果部署在高速云环境则需要打开此注释，目前先用IP
#    endPoint: oss-cn-jinan-sdhs-d01-a.ops.sdhs.cloud
    endPoint: 10.166.26.35
    accessKeyId: h1HEeliVnMImdxRH
    accessKeySecret: LpPPK7a9ZBRmRQyHIZJ5CmVxe7kLe8
    outAccessDomainName: https://${ruoyi.oss.bucketName}.${ruoyi.oss.endPoint}/
    upFolder: upload
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8000
#  port: 7075
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid,webthings,deal,platform
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
   # 初始化dispatcherServlet，默认-1未开启，0及以上为开启
  mvc:
     servlet:
       load-on-startup: 1
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    #    host: 127.0.0.1
    host: 10.166.157.190
#    host: 10.168.54.206
    # 端口，默认为6379
    port: 8081
    # 数据库索引
    database: 2
    # 密码
    password: sdj@&868qDn
    #    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 8760

# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain,com.zc.**.domain,com.tunnel.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: false
  # 请求前缀
  pathMapping: /dev-api

knife4j:
  enable: true

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

zc:
  # websocket 配置项
  websocket:
    # 端口
    port: 7789
    # 路径
    path: "/ws"
    # 客户端认证密码
    password: "zc&ws123"
    # 心跳周期
    interval: 60
    # 超时周期
    timeoutIntervals: 5

# 滑块验证码
aj:
  captcha:
    # 缓存类型
    cache-type: redis
    # blockPuzzle 滑块 clickWord 文字点选  default默认两者都实例化
    type: blockPuzzle
    # 右下角显示字
    water-mark: Athena
    # 校验滑动拼图允许误差偏移量(默认5像素)
    slip-offset: 5
    # aes加密坐标开启或者禁用(true|false)
    aes-status: true
    # 滑动干扰项(0/1/2)
    interference-options: 2

#万集接口对接
wj:
  imagePath: /eventimage
  url: http://10.3.16.4/img


#两级平台权限控制：管理站、高速云
authorize:
  name: GLZ
  #name: GSY
  gsy:
    host: http://211.168.65.230:8000
    tunnel_push_url: ${authorize.gsy.host}/platform/api/tunnelsAccept
    device_push_url: ${authorize.gsy.host}/platform/api/devicesAccept
  glz_host:
    wzb_glz_host: http://211.168.65.231:8000
    th_glz_host: http://211.168.65.232:8000
    mz_glz_host: http://211.168.65.233:8000
    yts_glz_host: http://211.168.65.234:8000
    jly_glz_host: http://211.168.65.235:8000
  #管理站部门id配置，用于管理站分发
  dept_id:
    #文祖北隧道管理站，太河隧道管理站，庙子隧道管理站，仰天山隧道管理站，九龙峪隧道管理站
    wzb_glz_dept_id: 10101
    th_glz_dept_id: 10301
    mz_glz_dept_id: 10701
    yts_glz_dept_id: 10702
    jly_glz_dept_id: 10703
    #设备控制接口
  #control_device_url:
#高速云端可控权限
platform:
  #control: AGREE #同意
  control: DISAGREE #不同意

#物联中台事件topic
eventTopic: "wq_tunnelEvent"
#物联中台设备状态topic
devStatusTopic: "wq_devStatusTopic"

#物联中台设备基础数据topic
tunnelDeviceBaseData: "tunnelDeviceBaseData"
#物联中台隧道基础数据topic
tunnelBaseData: "tunnelBaseData"

#应急车辆第三方接口
url:
  syn: "http://10.166.154.213:30001/equipment/CarInfo/list"
  edit: "http://10.166.154.213:30001/equipment/commandCenter/updateDispatchByDispatch"
  detail: "http://10.166.154.213:30001/equipment/deviceCar/getCarInfo"

#视频平台接口调用地址、组织机构ID
video-platform:
  address: "http://10.166.147.60:9021"
  deptId: "10000037"
