#------太河管理站生产环境配置-----
ruoyi:
  profile: /project/tunnel/uploadPath
spring:
  # 数据源配置
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://localhost:3306/tunnel-jq?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: root
        password: zc123456
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: Redis123!@#
  kafka:
    wulian:
      #正式环境部署地址
      bootstrap-servers: 10.166.139.204:9092,10.166.139.205:9092,10.166.139.206:9092


mqtt:
  #emqx地址+ MQTT协议端⼝ 1883 映射外网地址
  url: tcp://localhost:1883
