<template>
  <div>
    <iframe
      name="tuniframe"
      id="miframe"
      width="100%"
      class="mapHuaWei"
      frameborder="0"
      align="center"
      allowfullscreen="true"
      allow="autoplay"
      src="http://10.3.16.4/home"
    ></iframe>
  </div>
</template>
